citys = [{  
    "CityID": 1,  
    "name": "北京",  
    "ProID": 1,  
    "CitySort": 1  
}, {  
    "CityID": 2,  
    "name": "天津",  
    "ProID": 2,  
    "CitySort": 2  
}, {  
    "CityID": 3,  
    "name": "上海",  
    "ProID": 9,  
    "CitySort": 3  
}, {  
    "CityID": 4,  
    "name": "重庆",  
    "ProID": 27,  
    "CitySort": 4  
}, {  
    "CityID": 5,  
    "name": "邯郸",  
    "ProID": 3,  
    "CitySort": 5  
}, {  
    "CityID": 6,  
    "name": "石家庄",  
    "ProID": 3,  
    "CitySort": 6  
}, {  
    "CityID": 7,  
    "name": "保定",  
    "ProID": 3,  
    "CitySort": 7  
}, {  
    "CityID": 8,  
    "name": "张家口",  
    "ProID": 3,  
    "CitySort": 8  
}, {  
    "CityID": 9,  
    "name": "承德",  
    "ProID": 3,  
    "CitySort": 9  
}, {  
    "CityID": 10,  
    "name": "唐山",  
    "ProID": 3,  
    "CitySort": 10  
}, {  
    "CityID": 11,  
    "name": "廊坊",  
    "ProID": 3,  
    "CitySort": 11  
}, {  
    "CityID": 12,  
    "name": "沧州",  
    "ProID": 3,  
    "CitySort": 12  
}, {  
    "CityID": 13,  
    "name": "衡水",  
    "ProID": 3,  
    "CitySort": 13  
}, {  
    "CityID": 14,  
    "name": "邢台",  
    "ProID": 3,  
    "CitySort": 14  
}, {  
    "CityID": 16,  
    "name": "朔州",  
    "ProID": 4,  
    "CitySort": 16  
}, {  
    "CityID": 17,  
    "name": "忻州",  
    "ProID": 4,  
    "CitySort": 17  
}, {  
    "CityID": 18,  
    "name": "太原",  
    "ProID": 4,  
    "CitySort": 18  
}, {  
    "CityID": 19,  
    "name": "大同",  
    "ProID": 4,  
    "CitySort": 19  
}, {  
    "CityID": 20,  
    "name": "阳泉",  
    "ProID": 4,  
    "CitySort": 20  
}, {  
    "CityID": 21,  
    "name": "晋中",  
    "ProID": 4,  
    "CitySort": 21  
}, {  
    "CityID": 22,  
    "name": "长治",  
    "ProID": 4,  
    "CitySort": 22  
}, {  
    "CityID": 23,  
    "name": "晋城",  
    "ProID": 4,  
    "CitySort": 23  
}, {  
    "CityID": 24,  
    "name": "临汾",  
    "ProID": 4,  
    "CitySort": 24  
}, {  
    "CityID": 25,  
    "name": "吕梁",  
    "ProID": 4,  
    "CitySort": 25  
}, {  
    "CityID": 26,  
    "name": "运城",  
    "ProID": 4,  
    "CitySort": 26  
}, {  
    "CityID": 27,  
    "name": "沈阳",  
    "ProID": 6,  
    "CitySort": 27  
}, {  
    "CityID": 28,  
    "name": "铁岭",  
    "ProID": 6,  
    "CitySort": 28  
}, {  
    "CityID": 29,  
    "name": "大连",  
    "ProID": 6,  
    "CitySort": 29  
}, {  
    "CityID": 30,  
    "name": "鞍山",  
    "ProID": 6,  
    "CitySort": 30  
}, {  
    "CityID": 31,  
    "name": "抚顺",  
    "ProID": 6,  
    "CitySort": 31  
}, {  
    "CityID": 32,  
    "name": "本溪",  
    "ProID": 6,  
    "CitySort": 32  
}, {  
    "CityID": 33,  
    "name": "丹东",  
    "ProID": 6,  
    "CitySort": 33  
}, {  
    "CityID": 34,  
    "name": "锦州",  
    "ProID": 6,  
    "CitySort": 34  
}, {  
    "CityID": 35,  
    "name": "营口",  
    "ProID": 6,  
    "CitySort": 35  
}, {  
    "CityID": 36,  
    "name": "阜新",  
    "ProID": 6,  
    "CitySort": 36  
}, {  
    "CityID": 37,  
    "name": "辽阳",  
    "ProID": 6,  
    "CitySort": 37  
}, {  
    "CityID": 38,  
    "name": "朝阳",  
    "ProID": 6,  
    "CitySort": 38  
}, {  
    "CityID": 39,  
    "name": "盘锦",  
    "ProID": 6,  
    "CitySort": 39  
}, {  
    "CityID": 40,  
    "name": "葫芦岛",  
    "ProID": 6,  
    "CitySort": 40  
}, {  
    "CityID": 41,  
    "name": "长春",  
    "ProID": 7,  
    "CitySort": 41  
}, {  
    "CityID": 42,  
    "name": "吉林",  
    "ProID": 7,  
    "CitySort": 42  
}, {  
    "CityID": 43,  
    "name": "延边",  
    "ProID": 7,  
    "CitySort": 43  
}, {  
    "CityID": 44,  
    "name": "四平",  
    "ProID": 7,  
    "CitySort": 44  
}, {  
    "CityID": 45,  
    "name": "通化",  
    "ProID": 7,  
    "CitySort": 45  
}, {  
    "CityID": 46,  
    "name": "白城",  
    "ProID": 7,  
    "CitySort": 46  
}, {  
    "CityID": 47,  
    "name": "辽源",  
    "ProID": 7,  
    "CitySort": 47  
}, {  
    "CityID": 48,  
    "name": "松原",  
    "ProID": 7,  
    "CitySort": 48  
}, {  
    "CityID": 49,  
    "name": "白山",  
    "ProID": 7,  
    "CitySort": 49  
}, {  
    "CityID": 50,  
    "name": "哈尔滨",  
    "ProID": 8,  
    "CitySort": 50  
}, {  
    "CityID": 51,  
    "name": "齐齐哈尔",  
    "ProID": 8,  
    "CitySort": 51  
}, {  
    "CityID": 52,  
    "name": "鸡西",  
    "ProID": 8,  
    "CitySort": 52  
}, {  
    "CityID": 53,  
    "name": "牡丹江",  
    "ProID": 8,  
    "CitySort": 53  
}, {  
    "CityID": 54,  
    "name": "七台河",  
    "ProID": 8,  
    "CitySort": 54  
}, {  
    "CityID": 55,  
    "name": "佳木斯",  
    "ProID": 8,  
    "CitySort": 55  
}, {  
    "CityID": 56,  
    "name": "鹤岗",  
    "ProID": 8,  
    "CitySort": 56  
}, {  
    "CityID": 57,  
    "name": "双鸭山",  
    "ProID": 8,  
    "CitySort": 57  
}, {  
    "CityID": 58,  
    "name": "绥化",  
    "ProID": 8,  
    "CitySort": 58  
}, {  
    "CityID": 59,  
    "name": "黑河",  
    "ProID": 8,  
    "CitySort": 59  
}, {  
    "CityID": 60,  
    "name": "大兴安岭",  
    "ProID": 8,  
    "CitySort": 60  
}, {  
    "CityID": 61,  
    "name": "伊春",  
    "ProID": 8,  
    "CitySort": 61  
}, {  
    "CityID": 62,  
    "name": "大庆",  
    "ProID": 8,  
    "CitySort": 62  
}, {  
    "CityID": 63,  
    "name": "南京",  
    "ProID": 10,  
    "CitySort": 63  
}, {  
    "CityID": 64,  
    "name": "无锡",  
    "ProID": 10,  
    "CitySort": 64  
}, {  
    "CityID": 65,  
    "name": "镇江",  
    "ProID": 10,  
    "CitySort": 65  
}, {  
    "CityID": 66,  
    "name": "苏州",  
    "ProID": 10,  
    "CitySort": 66  
}, {  
    "CityID": 67,  
    "name": "南通",  
    "ProID": 10,  
    "CitySort": 67  
}, {  
    "CityID": 68,  
    "name": "扬州",  
    "ProID": 10,  
    "CitySort": 68  
}, {  
    "CityID": 69,  
    "name": "盐城",  
    "ProID": 10,  
    "CitySort": 69  
}, {  
    "CityID": 70,  
    "name": "徐州",  
    "ProID": 10,  
    "CitySort": 70  
}, {  
    "CityID": 71,  
    "name": "淮安",  
    "ProID": 10,  
    "CitySort": 71  
}, {  
    "CityID": 72,  
    "name": "连云港",  
    "ProID": 10,  
    "CitySort": 72  
}, {  
    "CityID": 73,  
    "name": "常州",  
    "ProID": 10,  
    "CitySort": 73  
}, {  
    "CityID": 74,  
    "name": "泰州",  
    "ProID": 10,  
    "CitySort": 74  
}, {  
    "CityID": 75,  
    "name": "宿迁",  
    "ProID": 10,  
    "CitySort": 75  
}, {  
    "CityID": 76,  
    "name": "舟山",  
    "ProID": 11,  
    "CitySort": 76  
}, {  
    "CityID": 77,  
    "name": "衢州",  
    "ProID": 11,  
    "CitySort": 77  
}, {  
    "CityID": 78,  
    "name": "杭州",  
    "ProID": 11,  
    "CitySort": 78  
}, {  
    "CityID": 79,  
    "name": "湖州",  
    "ProID": 11,  
    "CitySort": 79  
}, {  
    "CityID": 80,  
    "name": "嘉兴",  
    "ProID": 11,  
    "CitySort": 80  
}, {  
    "CityID": 81,  
    "name": "宁波",  
    "ProID": 11,  
    "CitySort": 81  
}, {  
    "CityID": 82,  
    "name": "绍兴",  
    "ProID": 11,  
    "CitySort": 82  
}, {  
    "CityID": 83,  
    "name": "温州",  
    "ProID": 11,  
    "CitySort": 83  
}, {  
    "CityID": 84,  
    "name": "丽水",  
    "ProID": 11,  
    "CitySort": 84  
}, {  
    "CityID": 85,  
    "name": "金华",  
    "ProID": 11,  
    "CitySort": 85  
}, {  
    "CityID": 86,  
    "name": "台州",  
    "ProID": 11,  
    "CitySort": 86  
}, {  
    "CityID": 87,  
    "name": "合肥",  
    "ProID": 12,  
    "CitySort": 87  
}, {  
    "CityID": 88,  
    "name": "芜湖",  
    "ProID": 12,  
    "CitySort": 88  
}, {  
    "CityID": 89,  
    "name": "蚌埠",  
    "ProID": 12,  
    "CitySort": 89  
}, {  
    "CityID": 90,  
    "name": "淮南",  
    "ProID": 12,  
    "CitySort": 90  
}, {  
    "CityID": 91,  
    "name": "马鞍山",  
    "ProID": 12,  
    "CitySort": 91  
}, {  
    "CityID": 92,  
    "name": "淮北",  
    "ProID": 12,  
    "CitySort": 92  
}, {  
    "CityID": 93,  
    "name": "铜陵",  
    "ProID": 12,  
    "CitySort": 93  
}, {  
    "CityID": 94,  
    "name": "安庆",  
    "ProID": 12,  
    "CitySort": 94  
}, {  
    "CityID": 95,  
    "name": "黄山",  
    "ProID": 12,  
    "CitySort": 95  
}, {  
    "CityID": 96,  
    "name": "滁州",  
    "ProID": 12,  
    "CitySort": 96  
}, {  
    "CityID": 97,  
    "name": "阜阳",  
    "ProID": 12,  
    "CitySort": 97  
}, {  
    "CityID": 98,  
    "name": "宿州",  
    "ProID": 12,  
    "CitySort": 98  
}, {  
    "CityID": 99,  
    "name": "巢湖",  
    "ProID": 12,  
    "CitySort": 99  
}, {  
    "CityID": 100,  
    "name": "六安",  
    "ProID": 12,  
    "CitySort": 100  
}, {  
    "CityID": 101,  
    "name": "亳州",  
    "ProID": 12,  
    "CitySort": 101  
}, {  
    "CityID": 102,  
    "name": "池州",  
    "ProID": 12,  
    "CitySort": 102  
}, {  
    "CityID": 103,  
    "name": "宣城",  
    "ProID": 12,  
    "CitySort": 103  
}, {  
    "CityID": 104,  
    "name": "福州",  
    "ProID": 13,  
    "CitySort": 104  
}, {  
    "CityID": 105,  
    "name": "厦门",  
    "ProID": 13,  
    "CitySort": 105  
}, {  
    "CityID": 106,  
    "name": "宁德",  
    "ProID": 13,  
    "CitySort": 106  
}, {  
    "CityID": 107,  
    "name": "莆田",  
    "ProID": 13,  
    "CitySort": 107  
}, {  
    "CityID": 108,  
    "name": "泉州",  
    "ProID": 13,  
    "CitySort": 108  
}, {  
    "CityID": 109,  
    "name": "漳州",  
    "ProID": 13,  
    "CitySort": 109  
}, {  
    "CityID": 110,  
    "name": "龙岩",  
    "ProID": 13,  
    "CitySort": 110  
}, {  
    "CityID": 111,  
    "name": "三明",  
    "ProID": 13,  
    "CitySort": 111  
}, {  
    "CityID": 112,  
    "name": "南平",  
    "ProID": 13,  
    "CitySort": 112  
}, {  
    "CityID": 113,  
    "name": "鹰潭",  
    "ProID": 14,  
    "CitySort": 113  
}, {  
    "CityID": 114,  
    "name": "新余",  
    "ProID": 14,  
    "CitySort": 114  
}, {  
    "CityID": 115,  
    "name": "南昌",  
    "ProID": 14,  
    "CitySort": 115  
}, {  
    "CityID": 116,  
    "name": "九江",  
    "ProID": 14,  
    "CitySort": 116  
}, {  
    "CityID": 117,  
    "name": "上饶",  
    "ProID": 14,  
    "CitySort": 117  
}, {  
    "CityID": 118,  
    "name": "抚州",  
    "ProID": 14,  
    "CitySort": 118  
}, {  
    "CityID": 119,  
    "name": "宜春",  
    "ProID": 14,  
    "CitySort": 119  
}, {  
    "CityID": 120,  
    "name": "吉安",  
    "ProID": 14,  
    "CitySort": 120  
}, {  
    "CityID": 121,  
    "name": "赣州",  
    "ProID": 14,  
    "CitySort": 121  
}, {  
    "CityID": 122,  
    "name": "景德镇",  
    "ProID": 14,  
    "CitySort": 122  
}, {  
    "CityID": 123,  
    "name": "萍乡",  
    "ProID": 14,  
    "CitySort": 123  
}, {  
    "CityID": 124,  
    "name": "菏泽",  
    "ProID": 15,  
    "CitySort": 124  
}, {  
    "CityID": 125,  
    "name": "济南",  
    "ProID": 15,  
    "CitySort": 125  
}, {  
    "CityID": 126,  
    "name": "青岛",  
    "ProID": 15,  
    "CitySort": 126  
}, {  
    "CityID": 127,  
    "name": "淄博",  
    "ProID": 15,  
    "CitySort": 127  
}, {  
    "CityID": 128,  
    "name": "德州",  
    "ProID": 15,  
    "CitySort": 128  
}, {  
    "CityID": 129,  
    "name": "烟台",  
    "ProID": 15,  
    "CitySort": 129  
}, {  
    "CityID": 130,  
    "name": "潍坊",  
    "ProID": 15,  
    "CitySort": 130  
}, {  
    "CityID": 131,  
    "name": "济宁",  
    "ProID": 15,  
    "CitySort": 131  
}, {  
    "CityID": 132,  
    "name": "泰安",  
    "ProID": 15,  
    "CitySort": 132  
}, {  
    "CityID": 133,  
    "name": "临沂",  
    "ProID": 15,  
    "CitySort": 133  
}, {  
    "CityID": 134,  
    "name": "滨州",  
    "ProID": 15,  
    "CitySort": 134  
}, {  
    "CityID": 135,  
    "name": "东营",  
    "ProID": 15,  
    "CitySort": 135  
}, {  
    "CityID": 136,  
    "name": "威海",  
    "ProID": 15,  
    "CitySort": 136  
}, {  
    "CityID": 137,  
    "name": "枣庄",  
    "ProID": 15,  
    "CitySort": 137  
}, {  
    "CityID": 138,  
    "name": "日照",  
    "ProID": 15,  
    "CitySort": 138  
}, {  
    "CityID": 139,  
    "name": "莱芜",  
    "ProID": 15,  
    "CitySort": 139  
}, {  
    "CityID": 140,  
    "name": "聊城",  
    "ProID": 15,  
    "CitySort": 140  
}, {  
    "CityID": 141,  
    "name": "商丘",  
    "ProID": 16,  
    "CitySort": 141  
}, {  
    "CityID": 142,  
    "name": "郑州",  
    "ProID": 16,  
    "CitySort": 142  
}, {  
    "CityID": 143,  
    "name": "安阳",  
    "ProID": 16,  
    "CitySort": 143  
}, {  
    "CityID": 144,  
    "name": "新乡",  
    "ProID": 16,  
    "CitySort": 144  
}, {  
    "CityID": 145,  
    "name": "许昌",  
    "ProID": 16,  
    "CitySort": 145  
}, {  
    "CityID": 146,  
    "name": "平顶山",  
    "ProID": 16,  
    "CitySort": 146  
}, {  
    "CityID": 147,  
    "name": "信阳",  
    "ProID": 16,  
    "CitySort": 147  
}, {  
    "CityID": 148,  
    "name": "南阳",  
    "ProID": 16,  
    "CitySort": 148  
}, {  
    "CityID": 149,  
    "name": "开封",  
    "ProID": 16,  
    "CitySort": 149  
}, {  
    "CityID": 150,  
    "name": "洛阳",  
    "ProID": 16,  
    "CitySort": 150  
}, {  
    "CityID": 151,  
    "name": "济源",  
    "ProID": 16,  
    "CitySort": 151  
}, {  
    "CityID": 152,  
    "name": "焦作",  
    "ProID": 16,  
    "CitySort": 152  
}, {  
    "CityID": 153,  
    "name": "鹤壁",  
    "ProID": 16,  
    "CitySort": 153  
}, {  
    "CityID": 154,  
    "name": "濮阳",  
    "ProID": 16,  
    "CitySort": 154  
}, {  
    "CityID": 155,  
    "name": "周口",  
    "ProID": 16,  
    "CitySort": 155  
}, {  
    "CityID": 156,  
    "name": "漯河",  
    "ProID": 16,  
    "CitySort": 156  
}, {  
    "CityID": 157,  
    "name": "驻马店",  
    "ProID": 16,  
    "CitySort": 157  
}, {  
    "CityID": 158,  
    "name": "三门峡",  
    "ProID": 16,  
    "CitySort": 158  
}, {  
    "CityID": 159,  
    "name": "武汉",  
    "ProID": 17,  
    "CitySort": 159  
}, {  
    "CityID": 160,  
    "name": "襄樊",  
    "ProID": 17,  
    "CitySort": 160  
}, {  
    "CityID": 161,  
    "name": "鄂州",  
    "ProID": 17,  
    "CitySort": 161  
}, {  
    "CityID": 162,  
    "name": "孝感",  
    "ProID": 17,  
    "CitySort": 162  
}, {  
    "CityID": 163,  
    "name": "黄冈",  
    "ProID": 17,  
    "CitySort": 163  
}, {  
    "CityID": 164,  
    "name": "黄石",  
    "ProID": 17,  
    "CitySort": 164  
}, {  
    "CityID": 165,  
    "name": "咸宁",  
    "ProID": 17,  
    "CitySort": 165  
}, {  
    "CityID": 166,  
    "name": "荆州",  
    "ProID": 17,  
    "CitySort": 166  
}, {  
    "CityID": 167,  
    "name": "宜昌",  
    "ProID": 17,  
    "CitySort": 167  
}, {  
    "CityID": 168,  
    "name": "恩施",  
    "ProID": 17,  
    "CitySort": 168  
}, {  
    "CityID": 169,  
    "name": "神农架林区",  
    "ProID": 17,  
    "CitySort": 169  
}, {  
    "CityID": 170,  
    "name": "十堰",  
    "ProID": 17,  
    "CitySort": 170  
}, {  
    "CityID": 171,  
    "name": "随州",  
    "ProID": 17,  
    "CitySort": 171  
}, {  
    "CityID": 172,  
    "name": "荆门",  
    "ProID": 17,  
    "CitySort": 172  
}, {  
    "CityID": 173,  
    "name": "仙桃",  
    "ProID": 17,  
    "CitySort": 173  
}, {  
    "CityID": 174,  
    "name": "天门",  
    "ProID": 17,  
    "CitySort": 174  
}, {  
    "CityID": 175,  
    "name": "潜江",  
    "ProID": 17,  
    "CitySort": 175  
}, {  
    "CityID": 176,  
    "name": "岳阳",  
    "ProID": 18,  
    "CitySort": 176  
}, {  
    "CityID": 177,  
    "name": "长沙",  
    "ProID": 18,  
    "CitySort": 177  
}, {  
    "CityID": 178,  
    "name": "湘潭",  
    "ProID": 18,  
    "CitySort": 178  
}, {  
    "CityID": 179,  
    "name": "株洲",  
    "ProID": 18,  
    "CitySort": 179  
}, {  
    "CityID": 180,  
    "name": "衡阳",  
    "ProID": 18,  
    "CitySort": 180  
}, {  
    "CityID": 181,  
    "name": "郴州",  
    "ProID": 18,  
    "CitySort": 181  
}, {  
    "CityID": 182,  
    "name": "常德",  
    "ProID": 18,  
    "CitySort": 182  
}, {  
    "CityID": 183,  
    "name": "益阳",  
    "ProID": 18,  
    "CitySort": 183  
}, {  
    "CityID": 184,  
    "name": "娄底",  
    "ProID": 18,  
    "CitySort": 184  
}, {  
    "CityID": 185,  
    "name": "邵阳",  
    "ProID": 18,  
    "CitySort": 185  
}, {  
    "CityID": 186,  
    "name": "湘西",  
    "ProID": 18,  
    "CitySort": 186  
}, {  
    "CityID": 187,  
    "name": "张家界",  
    "ProID": 18,  
    "CitySort": 187  
}, {  
    "CityID": 188,  
    "name": "怀化",  
    "ProID": 18,  
    "CitySort": 188  
}, {  
    "CityID": 189,  
    "name": "永州",  
    "ProID": 18,  
    "CitySort": 189  
}, {  
    "CityID": 190,  
    "name": "广州",  
    "ProID": 19,  
    "CitySort": 190  
}, {  
    "CityID": 191,  
    "name": "汕尾",  
    "ProID": 19,  
    "CitySort": 191  
}, {  
    "CityID": 192,  
    "name": "阳江",  
    "ProID": 19,  
    "CitySort": 192  
}, {  
    "CityID": 193,  
    "name": "揭阳",  
    "ProID": 19,  
    "CitySort": 193  
}, {  
    "CityID": 194,  
    "name": "茂名",  
    "ProID": 19,  
    "CitySort": 194  
}, {  
    "CityID": 195,  
    "name": "惠州",  
    "ProID": 19,  
    "CitySort": 195  
}, {  
    "CityID": 196,  
    "name": "江门",  
    "ProID": 19,  
    "CitySort": 196  
}, {  
    "CityID": 197,  
    "name": "韶关",  
    "ProID": 19,  
    "CitySort": 197  
}, {  
    "CityID": 198,  
    "name": "梅州",  
    "ProID": 19,  
    "CitySort": 198  
}, {  
    "CityID": 199,  
    "name": "汕头",  
    "ProID": 19,  
    "CitySort": 199  
}, {  
    "CityID": 200,  
    "name": "深圳",  
    "ProID": 19,  
    "CitySort": 200  
}, {  
    "CityID": 201,  
    "name": "珠海",  
    "ProID": 19,  
    "CitySort": 201  
}, {  
    "CityID": 202,  
    "name": "佛山",  
    "ProID": 19,  
    "CitySort": 202  
}, {  
    "CityID": 203,  
    "name": "肇庆",  
    "ProID": 19,  
    "CitySort": 203  
}, {  
    "CityID": 204,  
    "name": "湛江",  
    "ProID": 19,  
    "CitySort": 204  
}, {  
    "CityID": 205,  
    "name": "中山",  
    "ProID": 19,  
    "CitySort": 205  
}, {  
    "CityID": 206,  
    "name": "河源",  
    "ProID": 19,  
    "CitySort": 206  
}, {  
    "CityID": 207,  
    "name": "清远",  
    "ProID": 19,  
    "CitySort": 207  
}, {  
    "CityID": 208,  
    "name": "云浮",  
    "ProID": 19,  
    "CitySort": 208  
}, {  
    "CityID": 209,  
    "name": "潮州",  
    "ProID": 19,  
    "CitySort": 209  
}, {  
    "CityID": 210,  
    "name": "东莞",  
    "ProID": 19,  
    "CitySort": 210  
}, {  
    "CityID": 211,  
    "name": "兰州",  
    "ProID": 22,  
    "CitySort": 211  
}, {  
    "CityID": 212,  
    "name": "金昌",  
    "ProID": 22,  
    "CitySort": 212  
}, {  
    "CityID": 213,  
    "name": "白银",  
    "ProID": 22,  
    "CitySort": 213  
}, {  
    "CityID": 214,  
    "name": "天水",  
    "ProID": 22,  
    "CitySort": 214  
}, {  
    "CityID": 215,  
    "name": "嘉峪关",  
    "ProID": 22,  
    "CitySort": 215  
}, {  
    "CityID": 216,  
    "name": "武威",  
    "ProID": 22,  
    "CitySort": 216  
}, {  
    "CityID": 217,  
    "name": "张掖",  
    "ProID": 22,  
    "CitySort": 217  
}, {  
    "CityID": 218,  
    "name": "平凉",  
    "ProID": 22,  
    "CitySort": 218  
}, {  
    "CityID": 219,  
    "name": "酒泉",  
    "ProID": 22,  
    "CitySort": 219  
}, {  
    "CityID": 220,  
    "name": "庆阳",  
    "ProID": 22,  
    "CitySort": 220  
}, {  
    "CityID": 221,  
    "name": "定西",  
    "ProID": 22,  
    "CitySort": 221  
}, {  
    "CityID": 222,  
    "name": "陇南",  
    "ProID": 22,  
    "CitySort": 222  
}, {  
    "CityID": 223,  
    "name": "临夏",  
    "ProID": 22,  
    "CitySort": 223  
}, {  
    "CityID": 224,  
    "name": "甘南",  
    "ProID": 22,  
    "CitySort": 224  
}, {  
    "CityID": 225,  
    "name": "成都",  
    "ProID": 28,  
    "CitySort": 225  
}, {  
    "CityID": 226,  
    "name": "攀枝花",  
    "ProID": 28,  
    "CitySort": 226  
}, {  
    "CityID": 227,  
    "name": "自贡",  
    "ProID": 28,  
    "CitySort": 227  
}, {  
    "CityID": 228,  
    "name": "绵阳",  
    "ProID": 28,  
    "CitySort": 228  
}, {  
    "CityID": 229,  
    "name": "南充",  
    "ProID": 28,  
    "CitySort": 229  
}, {  
    "CityID": 230,  
    "name": "达州",  
    "ProID": 28,  
    "CitySort": 230  
}, {  
    "CityID": 231,  
    "name": "遂宁",  
    "ProID": 28,  
    "CitySort": 231  
}, {  
    "CityID": 232,  
    "name": "广安",  
    "ProID": 28,  
    "CitySort": 232  
}, {  
    "CityID": 233,  
    "name": "巴中",  
    "ProID": 28,  
    "CitySort": 233  
}, {  
    "CityID": 234,  
    "name": "泸州",  
    "ProID": 28,  
    "CitySort": 234  
}, {  
    "CityID": 235,  
    "name": "宜宾",  
    "ProID": 28,  
    "CitySort": 235  
}, {  
    "CityID": 236,  
    "name": "资阳",  
    "ProID": 28,  
    "CitySort": 236  
}, {  
    "CityID": 237,  
    "name": "内江",  
    "ProID": 28,  
    "CitySort": 237  
}, {  
    "CityID": 238,  
    "name": "乐山",  
    "ProID": 28,  
    "CitySort": 238  
}, {  
    "CityID": 239,  
    "name": "眉山",  
    "ProID": 28,  
    "CitySort": 239  
}, {  
    "CityID": 240,  
    "name": "凉山",  
    "ProID": 28,  
    "CitySort": 240  
}, {  
    "CityID": 241,  
    "name": "雅安",  
    "ProID": 28,  
    "CitySort": 241  
}, {  
    "CityID": 242,  
    "name": "甘孜",  
    "ProID": 28,  
    "CitySort": 242  
}, {  
    "CityID": 243,  
    "name": "阿坝",  
    "ProID": 28,  
    "CitySort": 243  
}, {  
    "CityID": 244,  
    "name": "德阳",  
    "ProID": 28,  
    "CitySort": 244  
}, {  
    "CityID": 245,  
    "name": "广元",  
    "ProID": 28,  
    "CitySort": 245  
}, {  
    "CityID": 246,  
    "name": "贵阳",  
    "ProID": 29,  
    "CitySort": 246  
}, {  
    "CityID": 247,  
    "name": "遵义",  
    "ProID": 29,  
    "CitySort": 247  
}, {  
    "CityID": 248,  
    "name": "安顺",  
    "ProID": 29,  
    "CitySort": 248  
}, {  
    "CityID": 249,  
    "name": "黔南",  
    "ProID": 29,  
    "CitySort": 249  
}, {  
    "CityID": 250,  
    "name": "黔东南",  
    "ProID": 29,  
    "CitySort": 250  
}, {  
    "CityID": 251,  
    "name": "铜仁",  
    "ProID": 29,  
    "CitySort": 251  
}, {  
    "CityID": 252,  
    "name": "毕节",  
    "ProID": 29,  
    "CitySort": 252  
}, {  
    "CityID": 253,  
    "name": "六盘水",  
    "ProID": 29,  
    "CitySort": 253  
}, {  
    "CityID": 254,  
    "name": "黔西南",  
    "ProID": 29,  
    "CitySort": 254  
}, {  
    "CityID": 255,  
    "name": "海口",  
    "ProID": 20,  
    "CitySort": 255  
}, {  
    "CityID": 256,  
    "name": "三亚",  
    "ProID": 20,  
    "CitySort": 256  
}, {  
    "CityID": 257,  
    "name": "五指山",  
    "ProID": 20,  
    "CitySort": 257  
}, {  
    "CityID": 258,  
    "name": "琼海",  
    "ProID": 20,  
    "CitySort": 258  
}, {  
    "CityID": 259,  
    "name": "儋州",  
    "ProID": 20,  
    "CitySort": 259  
}, {  
    "CityID": 260,  
    "name": "文昌",  
    "ProID": 20,  
    "CitySort": 260  
}, {  
    "CityID": 261,  
    "name": "万宁",  
    "ProID": 20,  
    "CitySort": 261  
}, {  
    "CityID": 262,  
    "name": "东方",  
    "ProID": 20,  
    "CitySort": 262  
}, {  
    "CityID": 263,  
    "name": "澄迈县",  
    "ProID": 20,  
    "CitySort": 263  
}, {  
    "CityID": 264,  
    "name": "定安县",  
    "ProID": 20,  
    "CitySort": 264  
}, {  
    "CityID": 265,  
    "name": "屯昌县",  
    "ProID": 20,  
    "CitySort": 265  
}, {  
    "CityID": 266,  
    "name": "临高县",  
    "ProID": 20,  
    "CitySort": 266  
}, {  
    "CityID": 267,  
    "name": "白沙",  
    "ProID": 20,  
    "CitySort": 267  
}, {  
    "CityID": 268,  
    "name": "昌江",  
    "ProID": 20,  
    "CitySort": 268  
}, {  
    "CityID": 269,  
    "name": "乐东",  
    "ProID": 20,  
    "CitySort": 269  
}, {  
    "CityID": 270,  
    "name": "陵水",  
    "ProID": 20,  
    "CitySort": 270  
}, {  
    "CityID": 271,  
    "name": "保亭",  
    "ProID": 20,  
    "CitySort": 271  
}, {  
    "CityID": 272,  
    "name": "琼中",  
    "ProID": 20,  
    "CitySort": 272  
}, {  
    "CityID": 273,  
    "name": "西双版纳",  
    "ProID": 30,  
    "CitySort": 273  
}, {  
    "CityID": 274,  
    "name": "德宏",  
    "ProID": 30,  
    "CitySort": 274  
}, {  
    "CityID": 275,  
    "name": "昭通",  
    "ProID": 30,  
    "CitySort": 275  
}, {  
    "CityID": 276,  
    "name": "昆明",  
    "ProID": 30,  
    "CitySort": 276  
}, {  
    "CityID": 277,  
    "name": "大理",  
    "ProID": 30,  
    "CitySort": 277  
}, {  
    "CityID": 278,  
    "name": "红河",  
    "ProID": 30,  
    "CitySort": 278  
}, {  
    "CityID": 279,  
    "name": "曲靖",  
    "ProID": 30,  
    "CitySort": 279  
}, {  
    "CityID": 280,  
    "name": "保山",  
    "ProID": 30,  
    "CitySort": 280  
}, {  
    "CityID": 281,  
    "name": "文山",  
    "ProID": 30,  
    "CitySort": 281  
}, {  
    "CityID": 282,  
    "name": "玉溪",  
    "ProID": 30,  
    "CitySort": 282  
}, {  
    "CityID": 283,  
    "name": "楚雄",  
    "ProID": 30,  
    "CitySort": 283  
}, {  
    "CityID": 284,  
    "name": "普洱",  
    "ProID": 30,  
    "CitySort": 284  
}, {  
    "CityID": 285,  
    "name": "临沧",  
    "ProID": 30,  
    "CitySort": 285  
}, {  
    "CityID": 286,  
    "name": "怒江",  
    "ProID": 30,  
    "CitySort": 286  
}, {  
    "CityID": 287,  
    "name": "迪庆",  
    "ProID": 30,  
    "CitySort": 287  
}, {  
    "CityID": 288,  
    "name": "丽江",  
    "ProID": 30,  
    "CitySort": 288  
}, {  
    "CityID": 289,  
    "name": "海北",  
    "ProID": 25,  
    "CitySort": 289  
}, {  
    "CityID": 290,  
    "name": "西宁",  
    "ProID": 25,  
    "CitySort": 290  
}, {  
    "CityID": 291,  
    "name": "海东",  
    "ProID": 25,  
    "CitySort": 291  
}, {  
    "CityID": 292,  
    "name": "黄南",  
    "ProID": 25,  
    "CitySort": 292  
}, {  
    "CityID": 293,  
    "name": "海南",  
    "ProID": 25,  
    "CitySort": 293  
}, {  
    "CityID": 294,  
    "name": "果洛",  
    "ProID": 25,  
    "CitySort": 294  
}, {  
    "CityID": 295,  
    "name": "玉树",  
    "ProID": 25,  
    "CitySort": 295  
}, {  
    "CityID": 296,  
    "name": "海西",  
    "ProID": 25,  
    "CitySort": 296  
}, {  
    "CityID": 297,  
    "name": "西安",  
    "ProID": 23,  
    "CitySort": 297  
}, {  
    "CityID": 298,  
    "name": "咸阳",  
    "ProID": 23,  
    "CitySort": 298  
}, {  
    "CityID": 299,  
    "name": "延安",  
    "ProID": 23,  
    "CitySort": 299  
}, {  
    "CityID": 300,  
    "name": "榆林",  
    "ProID": 23,  
    "CitySort": 300  
}, {  
    "CityID": 301,  
    "name": "渭南",  
    "ProID": 23,  
    "CitySort": 301  
}, {  
    "CityID": 302,  
    "name": "商洛",  
    "ProID": 23,  
    "CitySort": 302  
}, {  
    "CityID": 303,  
    "name": "安康",  
    "ProID": 23,  
    "CitySort": 303  
}, {  
    "CityID": 304,  
    "name": "汉中",  
    "ProID": 23,  
    "CitySort": 304  
}, {  
    "CityID": 305,  
    "name": "宝鸡",  
    "ProID": 23,  
    "CitySort": 305  
}, {  
    "CityID": 306,  
    "name": "铜川",  
    "ProID": 23,  
    "CitySort": 306  
}, {  
    "CityID": 307,  
    "name": "防城港",  
    "ProID": 21,  
    "CitySort": 307  
}, {  
    "CityID": 308,  
    "name": "南宁",  
    "ProID": 21,  
    "CitySort": 308  
}, {  
    "CityID": 309,  
    "name": "崇左",  
    "ProID": 21,  
    "CitySort": 309  
}, {  
    "CityID": 310,  
    "name": "来宾",  
    "ProID": 21,  
    "CitySort": 310  
}, {  
    "CityID": 311,  
    "name": "柳州",  
    "ProID": 21,  
    "CitySort": 311  
}, {  
    "CityID": 312,  
    "name": "桂林",  
    "ProID": 21,  
    "CitySort": 312  
}, {  
    "CityID": 313,  
    "name": "梧州",  
    "ProID": 21,  
    "CitySort": 313  
}, {  
    "CityID": 314,  
    "name": "贺州",  
    "ProID": 21,  
    "CitySort": 314  
}, {  
    "CityID": 315,  
    "name": "贵港",  
    "ProID": 21,  
    "CitySort": 315  
}, {  
    "CityID": 316,  
    "name": "玉林",  
    "ProID": 21,  
    "CitySort": 316  
}, {  
    "CityID": 317,  
    "name": "百色",  
    "ProID": 21,  
    "CitySort": 317  
}, {  
    "CityID": 318,  
    "name": "钦州",  
    "ProID": 21,  
    "CitySort": 318  
}, {  
    "CityID": 319,  
    "name": "河池",  
    "ProID": 21,  
    "CitySort": 319  
}, {  
    "CityID": 320,  
    "name": "北海",  
    "ProID": 21,  
    "CitySort": 320  
}, {  
    "CityID": 321,  
    "name": "拉萨",  
    "ProID": 31,  
    "CitySort": 321  
}, {  
    "CityID": 322,  
    "name": "日喀则",  
    "ProID": 31,  
    "CitySort": 322  
}, {  
    "CityID": 323,  
    "name": "山南",  
    "ProID": 31,  
    "CitySort": 323  
}, {  
    "CityID": 324,  
    "name": "林芝",  
    "ProID": 31,  
    "CitySort": 324  
}, {  
    "CityID": 325,  
    "name": "昌都",  
    "ProID": 31,  
    "CitySort": 325  
}, {  
    "CityID": 326,  
    "name": "那曲",  
    "ProID": 31,  
    "CitySort": 326  
}, {  
    "CityID": 327,  
    "name": "阿里",  
    "ProID": 31,  
    "CitySort": 327  
}, {  
    "CityID": 328,  
    "name": "银川",  
    "ProID": 26,  
    "CitySort": 328  
}, {  
    "CityID": 329,  
    "name": "石嘴山",  
    "ProID": 26,  
    "CitySort": 329  
}, {  
    "CityID": 330,  
    "name": "吴忠",  
    "ProID": 26,  
    "CitySort": 330  
}, {  
    "CityID": 331,  
    "name": "固原",  
    "ProID": 26,  
    "CitySort": 331  
}, {  
    "CityID": 332,  
    "name": "中卫",  
    "ProID": 26,  
    "CitySort": 332  
}, {  
    "CityID": 333,  
    "name": "塔城",  
    "ProID": 24,  
    "CitySort": 333  
}, {  
    "CityID": 334,  
    "name": "哈密",  
    "ProID": 24,  
    "CitySort": 334  
}, {  
    "CityID": 335,  
    "name": "和田",  
    "ProID": 24,  
    "CitySort": 335  
}, {  
    "CityID": 336,  
    "name": "阿勒泰",  
    "ProID": 24,  
    "CitySort": 336  
}, {  
    "CityID": 337,  
    "name": "克孜勒苏",  
    "ProID": 24,  
    "CitySort": 337  
}, {  
    "CityID": 338,  
    "name": "博尔塔拉",  
    "ProID": 24,  
    "CitySort": 338  
}, {  
    "CityID": 339,  
    "name": "克拉玛依",  
    "ProID": 24,  
    "CitySort": 339  
}, {  
    "CityID": 340,  
    "name": "乌鲁木齐",  
    "ProID": 24,  
    "CitySort": 340  
}, {  
    "CityID": 341,  
    "name": "石河子",  
    "ProID": 24,  
    "CitySort": 341  
}, {  
    "CityID": 342,  
    "name": "昌吉",  
    "ProID": 24,  
    "CitySort": 342  
}, {  
    "CityID": 343,  
    "name": "五家渠",  
    "ProID": 24,  
    "CitySort": 343  
}, {  
    "CityID": 344,  
    "name": "吐鲁番",  
    "ProID": 24,  
    "CitySort": 344  
}, {  
    "CityID": 345,  
    "name": "巴音郭楞",  
    "ProID": 24,  
    "CitySort": 345  
}, {  
    "CityID": 346,  
    "name": "阿克苏",  
    "ProID": 24,  
    "CitySort": 346  
}, {  
    "CityID": 347,  
    "name": "阿拉尔",  
    "ProID": 24,  
    "CitySort": 347  
}, {  
    "CityID": 348,  
    "name": "喀什",  
    "ProID": 24,  
    "CitySort": 348  
}, {  
    "CityID": 349,  
    "name": "图木舒克",  
    "ProID": 24,  
    "CitySort": 349  
}, {  
    "CityID": 350,  
    "name": "伊犁",  
    "ProID": 24,  
    "CitySort": 350  
}, {  
    "CityID": 351,  
    "name": "呼伦贝尔",  
    "ProID": 5,  
    "CitySort": 351  
}, {  
    "CityID": 352,  
    "name": "呼和浩特",  
    "ProID": 5,  
    "CitySort": 352  
}, {  
    "CityID": 353,  
    "name": "包头",  
    "ProID": 5,  
    "CitySort": 353  
}, {  
    "CityID": 354,  
    "name": "乌海",  
    "ProID": 5,  
    "CitySort": 354  
}, {  
    "CityID": 355,  
    "name": "乌兰察布",  
    "ProID": 5,  
    "CitySort": 355  
}, {  
    "CityID": 356,  
    "name": "通辽",  
    "ProID": 5,  
    "CitySort": 356  
}, {  
    "CityID": 357,  
    "name": "赤峰",  
    "ProID": 5,  
    "CitySort": 357  
}, {  
    "CityID": 358,  
    "name": "鄂尔多斯",  
    "ProID": 5,  
    "CitySort": 358  
}, {  
    "CityID": 359,  
    "name": "巴彦淖尔",  
    "ProID": 5,  
    "CitySort": 359  
}, {  
    "CityID": 360,  
    "name": "锡林郭勒盟",  
    "ProID": 5,  
    "CitySort": 360  
}, {  
    "CityID": 361,  
    "name": "兴安盟",  
    "ProID": 5,  
    "CitySort": 361  
}, {  
    "CityID": 362,  
    "name": "阿拉善盟",  
    "ProID": 5,  
    "CitySort": 362  
}, {  
    "CityID": 363,  
    "name": "台北",  
    "ProID": 32,  
    "CitySort": 363  
}, {  
    "CityID": 364,  
    "name": "高雄",  
    "ProID": 32,  
    "CitySort": 364  
}, {  
    "CityID": 365,  
    "name": "基隆",  
    "ProID": 32,  
    "CitySort": 365  
}, {  
    "CityID": 366,  
    "name": "台中",  
    "ProID": 32,  
    "CitySort": 366  
}, {  
    "CityID": 367,  
    "name": "台南",  
    "ProID": 32,  
    "CitySort": 367  
}, {  
    "CityID": 368,  
    "name": "新竹",  
    "ProID": 32,  
    "CitySort": 368  
}, {  
    "CityID": 369,  
    "name": "嘉义",  
    "ProID": 32,  
    "CitySort": 369  
}, {  
    "CityID": 370,  
    "name": "澳门",  
    "ProID": 33,  
    "CitySort": 370  
}, {  
    "CityID": 371,  
    "name": "香港",  
    "ProID": 34,  
    "CitySort": 371  
}]